import type { Service } from '../schema';

/**
 * Border & Identity Agency (BIA) Services
 *
 * Identity verification, border control, and immigration services.
 * Critical provider of identity services to other departments.
 */

export const biaServices: Service[] = [
  // =========================================================================
  // Wolf Identity Platform
  // =========================================================================
  {
    id: 'identity-verification-api',
    name: 'Identity Verification API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'wolf-identity',
    description:
      'Cross-government identity verification service. Validates identity documents and performs biometric checks.',
    documentation: 'https://docs.demo.gov.example/identity-verification',
    endpoint: 'https://api.identity.demo.gov.example/verify/v2',
    version: '2.5.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['document-check-service', 'biometric-matching-api', 'api-gateway'],
    consumedBy: ['citizen-portal', 'integration-hub', 'right-to-work-api'],
    relatedPatterns: ['identity-proofing', 'liveness-detection', 'document-validation'],
    status: 'live',
    lastUpdated: '2026-03-11',
    monthlyRequests: '22M',
    uptime: '99.98%',
    tags: ['identity', 'verification', 'cross-government', 'biometrics'],
  },
  {
    id: 'document-check-service',
    name: 'Document Checking Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'wolf-identity',
    description:
      'Validates identity documents (passports, driving licences, BRPs) against authoritative sources.',
    documentation: 'https://docs.demo.gov.example/document-check',
    endpoint: 'https://api.identity.demo.gov.example/documents/v2',
    version: '2.2.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['identity-verification-api', 'right-to-work-api'],
    relatedPatterns: ['document-validation', 'fraud-detection'],
    status: 'live',
    lastUpdated: '2026-03-08',
    monthlyRequests: '18M',
    tags: ['documents', 'validation', 'passports'],
  },
  {
    id: 'id-proofing-service',
    name: 'Identity Proofing Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'wolf-identity',
    description:
      'Establishes identity confidence levels through knowledge-based verification and trusted referee checks.',
    documentation: 'https://docs.demo.gov.example/id-proofing',
    endpoint: 'https://api.identity.demo.gov.example/proofing/v1',
    version: '1.4.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['identity-verification-api'],
    consumedBy: [],
    relatedPatterns: ['identity-proofing', 'confidence-levels'],
    status: 'live',
    lastUpdated: '2026-02-25',
    monthlyRequests: '3M',
    tags: ['identity', 'proofing', 'confidence'],
  },

  // =========================================================================
  // Bear Border Systems
  // =========================================================================
  {
    id: 'border-control-api',
    name: 'Border Control API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'bear-border',
    description:
      'Core API for border crossing checks, traveller verification, and entry/exit recording.',
    documentation: 'https://docs.demo.gov.example/border-control',
    endpoint: 'https://api.border.demo.gov.example/control/v3',
    version: '3.1.0',
    authentication: ['mtls'],
    dependsOn: ['watchlist-service', 'advance-passenger-info'],
    consumedBy: ['egate-service'],
    relatedPatterns: ['real-time-checks', 'watchlist-matching'],
    status: 'live',
    lastUpdated: '2026-03-10',
    monthlyRequests: '85M',
    uptime: '99.99%',
    tags: ['border', 'control', 'immigration'],
  },
  {
    id: 'advance-passenger-info',
    name: 'Advance Passenger Information',
    type: 'event-stream',
    departmentId: 'bia',
    teamId: 'bear-border',
    description:
      'Receives and processes advance passenger data from carriers before arrival.',
    documentation: 'https://docs.demo.gov.example/api',
    endpoint: 'https://api.border.demo.gov.example/api/v2',
    version: '2.4.0',
    authentication: ['mtls'],
    dependsOn: [],
    consumedBy: ['border-control-api', 'watchlist-service'],
    relatedPatterns: ['event-streaming', 'pre-arrival-processing'],
    status: 'live',
    lastUpdated: '2026-03-05',
    monthlyRequests: '120M',
    tags: ['api', 'carriers', 'advance-data'],
  },
  {
    id: 'watchlist-service',
    name: 'Watchlist Checking Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'bear-border',
    description:
      'Real-time checking against security and immigration watchlists.',
    documentation: 'https://docs.demo.gov.example/watchlist',
    endpoint: 'https://api.border.demo.gov.example/watchlist/v2',
    version: '2.0.0',
    authentication: ['mtls'],
    dependsOn: [],
    consumedBy: ['border-control-api', 'advance-passenger-info'],
    relatedPatterns: ['real-time-matching', 'fuzzy-matching'],
    status: 'live',
    lastUpdated: '2026-02-28',
    monthlyRequests: '200M',
    uptime: '99.999%',
    tags: ['watchlist', 'security', 'matching'],
  },
  {
    id: 'egate-service',
    name: 'E-Gate Integration Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'bear-border',
    description:
      'Manages automated e-gate processing at ports and airports.',
    documentation: 'https://docs.demo.gov.example/egates',
    endpoint: 'https://api.border.demo.gov.example/egates/v1',
    version: '1.8.0',
    authentication: ['mtls'],
    dependsOn: ['border-control-api', 'facial-recognition-service'],
    consumedBy: [],
    relatedPatterns: ['real-time-processing', 'biometric-verification'],
    status: 'live',
    lastUpdated: '2026-02-20',
    monthlyRequests: '45M',
    tags: ['egates', 'automated', 'biometrics'],
  },

  // =========================================================================
  // Lynx Document Services
  // =========================================================================
  {
    id: 'passport-application-api',
    name: 'Passport Application API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'lynx-documents',
    description:
      'Handles passport applications, renewals, and status tracking.',
    documentation: 'https://docs.demo.gov.example/passport-application',
    endpoint: 'https://api.identity.demo.gov.example/passport/v2',
    version: '2.6.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['gov-notify', 'gov-pay', 'biometric-enrolment'],
    consumedBy: [],
    relatedPatterns: ['document-upload', 'async-processing', 'payment-flow'],
    status: 'live',
    lastUpdated: '2026-03-09',
    monthlyRequests: '2.5M',
    tags: ['passport', 'applications', 'citizen-facing'],
  },
  {
    id: 'visa-status-api',
    name: 'Visa Status API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'lynx-documents',
    description:
      'Provides visa status and entitlement information for authorised enquirers.',
    documentation: 'https://docs.demo.gov.example/visa-status',
    endpoint: 'https://api.identity.demo.gov.example/visa/v2',
    version: '2.1.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['right-to-work-api', 'right-to-rent-api'],
    relatedPatterns: ['consent-management', 'data-minimisation'],
    status: 'live',
    lastUpdated: '2026-03-03',
    monthlyRequests: '8M',
    tags: ['visa', 'immigration', 'status'],
  },
  {
    id: 'right-to-work-api',
    name: 'Right to Work Check API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'lynx-documents',
    description:
      'Enables employers to verify right to work status for job applicants.',
    documentation: 'https://docs.demo.gov.example/right-to-work',
    endpoint: 'https://api.identity.demo.gov.example/rtw/v2',
    version: '2.3.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['visa-status-api', 'document-check-service', 'identity-verification-api'],
    consumedBy: [],
    relatedPatterns: ['employer-checking', 'share-codes'],
    status: 'live',
    lastUpdated: '2026-03-07',
    monthlyRequests: '6M',
    tags: ['right-to-work', 'employers', 'verification'],
  },
  {
    id: 'right-to-rent-api',
    name: 'Right to Rent Check API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'lynx-documents',
    description:
      'Enables landlords to verify right to rent status for prospective tenants.',
    documentation: 'https://docs.demo.gov.example/right-to-rent',
    endpoint: 'https://api.identity.demo.gov.example/rtr/v1',
    version: '1.5.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['visa-status-api', 'income-verification-api'],
    consumedBy: [],
    relatedPatterns: ['landlord-checking', 'share-codes'],
    status: 'live',
    lastUpdated: '2026-02-28',
    monthlyRequests: '1.5M',
    tags: ['right-to-rent', 'landlords', 'verification'],
  },
  {
    id: 'document-issuance',
    name: 'Document Issuance Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'lynx-documents',
    description:
      'Manages the creation and dispatch of physical and digital identity documents.',
    documentation: 'https://docs.demo.gov.example/document-issuance',
    endpoint: 'https://api.identity.demo.gov.example/issuance/v1',
    version: '1.3.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['passport-application-api'],
    relatedPatterns: ['secure-printing', 'digital-credentials'],
    status: 'live',
    lastUpdated: '2026-02-15',
    monthlyRequests: '800K',
    tags: ['issuance', 'documents', 'printing'],
  },

  // =========================================================================
  // Fox Biometrics Unit
  // =========================================================================
  {
    id: 'biometric-matching-api',
    name: 'Biometric Matching API',
    type: 'api',
    departmentId: 'bia',
    teamId: 'fox-biometrics',
    description:
      'High-accuracy fingerprint and facial matching against the national biometric database.',
    documentation: 'https://docs.demo.gov.example/biometric-matching',
    endpoint: 'https://api.biometrics.demo.gov.example/match/v2',
    version: '2.0.0',
    authentication: ['mtls'],
    dependsOn: [],
    consumedBy: ['identity-verification-api', 'border-control-api'],
    relatedPatterns: ['biometric-matching', 'threshold-tuning'],
    status: 'live',
    lastUpdated: '2026-03-06',
    monthlyRequests: '35M',
    uptime: '99.99%',
    tags: ['biometrics', 'matching', 'fingerprints', 'facial'],
  },
  {
    id: 'facial-recognition-service',
    name: 'Facial Recognition Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'fox-biometrics',
    description:
      'Real-time facial recognition for e-gates and identity verification.',
    documentation: 'https://docs.demo.gov.example/facial-recognition',
    endpoint: 'https://api.biometrics.demo.gov.example/face/v2',
    version: '2.2.0',
    authentication: ['mtls'],
    dependsOn: ['biometric-matching-api'],
    consumedBy: ['egate-service', 'identity-verification-api'],
    relatedPatterns: ['liveness-detection', 'presentation-attack-detection'],
    status: 'live',
    lastUpdated: '2026-03-04',
    monthlyRequests: '50M',
    tags: ['facial', 'recognition', 'biometrics', 'real-time'],
  },
  {
    id: 'biometric-enrolment',
    name: 'Biometric Enrolment Service',
    type: 'api',
    departmentId: 'bia',
    teamId: 'fox-biometrics',
    description:
      'Captures and stores biometric data during document applications and visa processes.',
    documentation: 'https://docs.demo.gov.example/biometric-enrolment',
    endpoint: 'https://api.biometrics.demo.gov.example/enrol/v1',
    version: '1.6.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['passport-application-api'],
    relatedPatterns: ['biometric-capture', 'quality-checks'],
    status: 'live',
    lastUpdated: '2026-02-22',
    monthlyRequests: '4M',
    tags: ['biometrics', 'enrolment', 'capture'],
  },
];

export default biaServices;
