import type { Service } from '../schema';

/**
 * Department for Citizen Support (DCS) Services
 *
 * Welfare, benefits, and citizen support services.
 * Heavy consumers of cross-government shared services.
 */

export const dcsServices: Service[] = [
  // =========================================================================
  // Puffin Delivery Squad
  // =========================================================================
  {
    id: 'citizen-portal',
    name: 'Citizen Support Portal',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'puffin-delivery',
    description:
      'Main citizen-facing service for applying for benefits, checking status, and managing support. 2M+ monthly users.',
    documentation: 'https://docs.demo.gov.example/citizen-portal',
    endpoint: 'https://support.demo.gov.example',
    version: '8.2.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: [
      'design-system',
      'component-library',
      'gov-notify',
      'gov-pay',
      'eligibility-api',
      'identity-verification-api',
    ],
    consumedBy: [],
    relatedPatterns: ['accessible-forms', 'progressive-enhancement', 'session-management'],
    status: 'live',
    lastUpdated: '2026-03-14',
    monthlyRequests: '85M',
    uptime: '99.9%',
    tags: ['citizen-facing', 'benefits', 'portal', 'frontend'],
  },
  {
    id: 'eligibility-api',
    name: 'Citizen Eligibility API',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'puffin-delivery',
    description:
      'Determines citizen eligibility for support programmes based on income, household, and circumstances.',
    documentation: 'https://docs.demo.gov.example/eligibility',
    endpoint: 'https://api.citizen-support.demo.gov.example/eligibility/v2',
    version: '2.4.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['calculation-engine', 'income-verification-api', 'api-gateway'],
    consumedBy: ['citizen-portal', 'case-management', 'integration-hub'],
    relatedPatterns: ['rules-engine', 'async-eligibility-check', 'caching-strategy'],
    status: 'live',
    lastUpdated: '2026-03-08',
    monthlyRequests: '12M',
    uptime: '99.95%',
    tags: ['eligibility', 'benefits', 'rules', 'api'],
  },
  {
    id: 'case-management',
    name: 'Case Management System',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'puffin-delivery',
    description:
      'Internal system for managing citizen cases, work items, and decision recording.',
    documentation: 'https://docs.demo.gov.example/case-management',
    endpoint: 'https://cases.internal.demo.gov.example',
    version: '5.1.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['eligibility-api', 'gov-notify', 'delivery-receipts', 'refund-service'],
    consumedBy: [],
    relatedPatterns: ['event-sourcing', 'audit-logging', 'workflow-patterns'],
    status: 'live',
    lastUpdated: '2026-03-11',
    tags: ['internal', 'case-management', 'workflow'],
  },
  {
    id: 'application-service',
    name: 'Benefit Application Service',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'puffin-delivery',
    description:
      'Handles benefit application submissions, validation, and routing to appropriate teams.',
    documentation: 'https://docs.demo.gov.example/applications',
    endpoint: 'https://api.citizen-support.demo.gov.example/applications/v1',
    version: '3.0.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['gov-notify', 'eligibility-api'],
    consumedBy: ['citizen-portal', 'case-management'],
    relatedPatterns: ['saga-pattern', 'idempotency-keys', 'document-upload'],
    status: 'live',
    lastUpdated: '2026-02-25',
    monthlyRequests: '1.8M',
    tags: ['applications', 'benefits', 'submissions'],
  },

  // =========================================================================
  // Cormorant Data Team
  // =========================================================================
  {
    id: 'citizen-data-platform',
    name: 'Citizen Data Platform',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'cormorant-data',
    description:
      'Central data store for citizen records, providing the golden record view across DCS systems.',
    documentation: 'https://docs.demo.gov.example/citizen-data',
    endpoint: 'https://data.internal.demo.gov.example',
    version: '4.2.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['eligibility-api', 'calculation-engine', 'reporting-api'],
    relatedPatterns: ['data-mesh', 'event-sourcing', 'gdpr-compliance'],
    status: 'live',
    lastUpdated: '2026-03-06',
    tags: ['data', 'platform', 'citizen-records'],
  },
  {
    id: 'calculation-engine',
    name: 'Benefit Calculation Engine',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'cormorant-data',
    description:
      'Calculates benefit entitlements based on legislation rules. Versioned rules support historical calculations.',
    documentation: 'https://docs.demo.gov.example/calculation-engine',
    endpoint: 'https://api.citizen-support.demo.gov.example/calculations/v3',
    version: '3.8.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['citizen-data-platform'],
    consumedBy: ['eligibility-api', 'case-management'],
    relatedPatterns: ['rules-engine', 'versioned-calculations'],
    status: 'live',
    lastUpdated: '2026-03-01',
    monthlyRequests: '25M',
    tags: ['calculations', 'benefits', 'rules-engine'],
  },
  {
    id: 'reporting-api',
    name: 'DCS Reporting API',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'cormorant-data',
    description:
      'Provides aggregated reporting data for management information and ministerial briefings.',
    documentation: 'https://docs.demo.gov.example/dcs-reporting',
    endpoint: 'https://api.citizen-support.demo.gov.example/reporting/v1',
    version: '2.1.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['citizen-data-platform', 'reconciliation-api'],
    consumedBy: [],
    relatedPatterns: ['data-aggregation', 'caching-strategy'],
    status: 'live',
    lastUpdated: '2026-02-15',
    monthlyRequests: '500K',
    tags: ['reporting', 'analytics', 'management-information'],
  },
  {
    id: 'data-quality-service',
    name: 'Data Quality Service',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'cormorant-data',
    description:
      'Monitors and reports on data quality metrics. Identifies duplicates and data anomalies.',
    documentation: 'https://docs.demo.gov.example/data-quality',
    endpoint: 'https://api.citizen-support.demo.gov.example/data-quality/v1',
    version: '1.4.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['citizen-data-platform'],
    consumedBy: [],
    relatedPatterns: ['data-validation', 'monitoring-patterns'],
    status: 'live',
    lastUpdated: '2026-01-20',
    tags: ['data-quality', 'monitoring', 'validation'],
  },

  // =========================================================================
  // Gannet Platform Engineering
  // =========================================================================
  {
    id: 'dcs-platform',
    name: 'DCS Hosting Platform',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'gannet-platform',
    description:
      'Department-specific hosting platform built on top of Government Cloud Platform.',
    documentation: 'https://docs.demo.gov.example/dcs-platform',
    version: '3.0.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['cloud-platform'],
    consumedBy: [],
    relatedPatterns: ['twelve-factor-app', 'infrastructure-as-code'],
    status: 'live',
    lastUpdated: '2026-02-28',
    tags: ['infrastructure', 'hosting', 'platform'],
  },
  {
    id: 'monitoring-stack',
    name: 'DCS Monitoring Stack',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'gannet-platform',
    description:
      'Prometheus, Grafana, and alerting infrastructure for DCS services.',
    documentation: 'https://docs.demo.gov.example/dcs-monitoring',
    version: '2.5.0',
    dependsOn: ['dcs-platform'],
    consumedBy: [],
    relatedPatterns: ['observability-patterns', 'alerting-strategy'],
    status: 'live',
    lastUpdated: '2026-02-10',
    tags: ['monitoring', 'observability', 'alerting'],
  },
  {
    id: 'ci-cd-service',
    name: 'DCS CI/CD Service',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'gannet-platform',
    description:
      'GitHub Actions-based CI/CD with security scanning, accessibility testing, and automated deployment.',
    documentation: 'https://docs.demo.gov.example/dcs-cicd',
    version: '4.1.0',
    dependsOn: ['dcs-platform', 'accessibility-checker'],
    consumedBy: [],
    relatedPatterns: ['continuous-deployment', 'security-scanning'],
    status: 'live',
    lastUpdated: '2026-03-03',
    tags: ['ci-cd', 'deployment', 'automation'],
  },

  // =========================================================================
  // Tern Integration Hub
  // =========================================================================
  {
    id: 'integration-hub',
    name: 'DCS Integration Hub',
    type: 'platform',
    departmentId: 'dcs',
    teamId: 'tern-integration',
    description:
      'Message broker and API orchestration layer for cross-department data sharing.',
    documentation: 'https://docs.demo.gov.example/integration-hub',
    endpoint: 'https://integration.citizen-support.demo.gov.example',
    version: '2.3.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['eligibility-api'],
    consumedBy: ['income-verification-api', 'identity-verification-api'],
    relatedPatterns: ['event-driven-integration', 'saga-pattern', 'circuit-breaker'],
    status: 'live',
    lastUpdated: '2026-03-07',
    monthlyRequests: '35M',
    tags: ['integration', 'messaging', 'orchestration'],
  },
  {
    id: 'partner-gateway',
    name: 'Partner Gateway',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'tern-integration',
    description:
      'Secure gateway for external partners (local authorities, housing associations) to submit data.',
    documentation: 'https://docs.demo.gov.example/partner-gateway',
    endpoint: 'https://partners.citizen-support.demo.gov.example/api/v1',
    version: '1.5.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['integration-hub'],
    consumedBy: [],
    relatedPatterns: ['api-gateway-pattern', 'partner-onboarding'],
    status: 'live',
    lastUpdated: '2026-02-22',
    monthlyRequests: '5M',
    tags: ['partners', 'external', 'gateway'],
  },
  {
    id: 'data-exchange-api',
    name: 'Cross-Department Data Exchange',
    type: 'api',
    departmentId: 'dcs',
    teamId: 'tern-integration',
    description:
      'Standardised API for requesting and receiving data from other government departments.',
    documentation: 'https://docs.demo.gov.example/data-exchange',
    endpoint: 'https://api.citizen-support.demo.gov.example/exchange/v2',
    version: '2.0.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['integration-hub'],
    consumedBy: ['eligibility-api'],
    relatedPatterns: ['data-sharing-agreements', 'consent-management'],
    status: 'live',
    lastUpdated: '2026-02-18',
    monthlyRequests: '8M',
    tags: ['data-exchange', 'cross-government', 'integration'],
  },
];

export default dcsServices;
