import type { Service } from '../schema';

/**
 * Revenue & Taxation Service (RTS) Services
 *
 * Tax collection, income verification, and compliance services.
 * Major data provider to other departments.
 */

export const rtsServices: Service[] = [
  // =========================================================================
  // Falcon Core Systems
  // =========================================================================
  {
    id: 'tax-calculation-engine',
    name: 'Tax Calculation Engine',
    type: 'api',
    departmentId: 'rts',
    teamId: 'falcon-core',
    description:
      'Core engine for calculating income tax, national insurance, and other tax obligations.',
    documentation: 'https://docs.demo.gov.example/tax-calculation',
    endpoint: 'https://api.revenue.demo.gov.example/calculations/v3',
    version: '3.12.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['rts-data-lake'],
    consumedBy: ['employer-api', 'assessment-service'],
    relatedPatterns: ['rules-engine', 'versioned-calculations', 'audit-logging'],
    status: 'live',
    lastUpdated: '2026-03-10',
    monthlyRequests: '180M',
    uptime: '99.99%',
    tags: ['tax', 'calculations', 'core-system'],
  },
  {
    id: 'assessment-service',
    name: 'Tax Assessment Service',
    type: 'api',
    departmentId: 'rts',
    teamId: 'falcon-core',
    description:
      'Manages self-assessment submissions, calculations, and tax return processing.',
    documentation: 'https://docs.demo.gov.example/assessment',
    endpoint: 'https://api.revenue.demo.gov.example/assessment/v2',
    version: '2.8.0',
    authentication: ['oauth2-authorization-code', 'oauth2-client-credentials'],
    dependsOn: ['tax-calculation-engine', 'tax-account-api'],
    consumedBy: [],
    relatedPatterns: ['document-upload', 'async-processing', 'audit-logging'],
    status: 'live',
    lastUpdated: '2026-03-05',
    monthlyRequests: '15M',
    tags: ['assessment', 'self-assessment', 'tax-returns'],
  },
  {
    id: 'tax-account-api',
    name: 'Tax Account API',
    type: 'api',
    departmentId: 'rts',
    teamId: 'falcon-core',
    description:
      'Provides tax account balances, payment history, and liability information.',
    documentation: 'https://docs.demo.gov.example/tax-account',
    endpoint: 'https://api.revenue.demo.gov.example/accounts/v2',
    version: '2.4.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['payment-allocation'],
    consumedBy: ['assessment-service'],
    relatedPatterns: ['account-management', 'balance-calculation'],
    status: 'live',
    lastUpdated: '2026-02-28',
    monthlyRequests: '45M',
    tags: ['accounts', 'balances', 'payments'],
  },
  {
    id: 'payment-allocation',
    name: 'Payment Allocation Service',
    type: 'api',
    departmentId: 'rts',
    teamId: 'falcon-core',
    description:
      'Allocates incoming payments to appropriate tax liabilities using configurable rules.',
    documentation: 'https://docs.demo.gov.example/payment-allocation',
    endpoint: 'https://api.revenue.demo.gov.example/allocation/v1',
    version: '1.6.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['tax-account-api'],
    relatedPatterns: ['payment-allocation-rules', 'idempotency-keys'],
    status: 'live',
    lastUpdated: '2026-02-15',
    monthlyRequests: '12M',
    tags: ['payments', 'allocation', 'finance'],
  },

  // =========================================================================
  // Kestrel API Team
  // =========================================================================
  {
    id: 'income-verification-api',
    name: 'Income Verification API',
    type: 'api',
    departmentId: 'rts',
    teamId: 'kestrel-api',
    description:
      'Provides verified income data to authorised government departments. Key integration for benefit eligibility.',
    documentation: 'https://docs.demo.gov.example/income-verification',
    endpoint: 'https://api.revenue.demo.gov.example/income/v2',
    version: '2.3.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['rti-processor', 'api-gateway'],
    consumedBy: ['eligibility-api', 'integration-hub', 'right-to-rent-api'],
    relatedPatterns: ['consent-management', 'data-minimisation', 'caching-strategy'],
    status: 'live',
    lastUpdated: '2026-03-12',
    monthlyRequests: '28M',
    uptime: '99.97%',
    tags: ['income', 'verification', 'cross-government', 'api'],
  },
  {
    id: 'employer-api',
    name: 'Employer Services API',
    type: 'api',
    departmentId: 'rts',
    teamId: 'kestrel-api',
    description:
      'APIs for employers to submit PAYE data, query employee tax codes, and manage payroll submissions.',
    documentation: 'https://docs.demo.gov.example/employer-api',
    endpoint: 'https://api.revenue.demo.gov.example/employer/v3',
    version: '3.5.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['tax-calculation-engine'],
    consumedBy: [],
    relatedPatterns: ['batch-processing', 'file-upload', 'validation-rules'],
    status: 'live',
    lastUpdated: '2026-03-08',
    monthlyRequests: '95M',
    tags: ['employer', 'paye', 'payroll'],
  },
  {
    id: 'agent-services-api',
    name: 'Agent Services API',
    type: 'api',
    departmentId: 'rts',
    teamId: 'kestrel-api',
    description:
      'Enables tax agents and accountants to act on behalf of clients for tax matters.',
    documentation: 'https://docs.demo.gov.example/agent-services',
    endpoint: 'https://api.revenue.demo.gov.example/agents/v2',
    version: '2.2.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['tax-account-api'],
    consumedBy: [],
    relatedPatterns: ['delegation-patterns', 'authorisation-management'],
    status: 'live',
    lastUpdated: '2026-02-20',
    monthlyRequests: '18M',
    tags: ['agents', 'accountants', 'delegation'],
  },
  {
    id: 'rts-developer-portal',
    name: 'RTS Developer Portal',
    type: 'platform',
    departmentId: 'rts',
    teamId: 'kestrel-api',
    description:
      'Self-service portal for software developers to register applications and access RTS APIs.',
    documentation: 'https://developer.revenue.demo.gov.example',
    endpoint: 'https://developer.revenue.demo.gov.example',
    version: '4.0.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['design-system'],
    consumedBy: [],
    relatedPatterns: ['developer-experience', 'api-documentation'],
    status: 'live',
    lastUpdated: '2026-03-01',
    tags: ['developer-portal', 'documentation', 'onboarding'],
  },

  // =========================================================================
  // Merlin Data Platform
  // =========================================================================
  {
    id: 'rts-data-lake',
    name: 'RTS Data Lake',
    type: 'platform',
    departmentId: 'rts',
    teamId: 'merlin-data',
    description:
      'Central data lake for all RTS data. Supports real-time and batch analytics.',
    documentation: 'https://docs.demo.gov.example/rts-data-lake',
    version: '5.0.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['tax-calculation-engine', 'analytics-platform', 'fraud-detection-api'],
    relatedPatterns: ['data-lake-architecture', 'data-governance'],
    status: 'live',
    lastUpdated: '2026-02-25',
    tags: ['data-lake', 'analytics', 'big-data'],
  },
  {
    id: 'rti-processor',
    name: 'Real-Time Information Processor',
    type: 'event-stream',
    departmentId: 'rts',
    teamId: 'merlin-data',
    description:
      'Processes real-time PAYE submissions from employers. Handles 50M+ records monthly.',
    documentation: 'https://docs.demo.gov.example/rti-processor',
    version: '3.2.0',
    dependsOn: ['rts-data-lake'],
    consumedBy: ['income-verification-api'],
    relatedPatterns: ['event-streaming', 'exactly-once-processing'],
    status: 'live',
    lastUpdated: '2026-03-04',
    monthlyRequests: '50M',
    tags: ['real-time', 'streaming', 'paye', 'rti'],
  },
  {
    id: 'analytics-platform',
    name: 'RTS Analytics Platform',
    type: 'platform',
    departmentId: 'rts',
    teamId: 'merlin-data',
    description:
      'Business intelligence and analytics platform for RTS operational and strategic reporting.',
    documentation: 'https://docs.demo.gov.example/rts-analytics',
    version: '2.8.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['rts-data-lake'],
    consumedBy: [],
    relatedPatterns: ['data-warehousing', 'dashboard-patterns'],
    status: 'live',
    lastUpdated: '2026-02-18',
    tags: ['analytics', 'reporting', 'bi'],
  },
  {
    id: 'data-governance-tools',
    name: 'Data Governance Toolkit',
    type: 'platform',
    departmentId: 'rts',
    teamId: 'merlin-data',
    description:
      'Tools for managing data lineage, quality, and governance across RTS systems.',
    documentation: 'https://docs.demo.gov.example/data-governance',
    version: '1.5.0',
    dependsOn: ['rts-data-lake'],
    consumedBy: [],
    relatedPatterns: ['data-lineage', 'data-quality'],
    status: 'live',
    lastUpdated: '2026-01-30',
    tags: ['governance', 'data-quality', 'lineage'],
  },

  // =========================================================================
  // Osprey Compliance
  // =========================================================================
  {
    id: 'fraud-detection-api',
    name: 'Fraud Detection API',
    type: 'api',
    departmentId: 'rts',
    teamId: 'osprey-compliance',
    description:
      'ML-powered fraud detection for tax submissions. Provides risk scores and anomaly alerts.',
    documentation: 'https://docs.demo.gov.example/fraud-detection',
    endpoint: 'https://api.revenue.demo.gov.example/fraud/v2',
    version: '2.1.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['rts-data-lake', 'risk-scoring-service'],
    consumedBy: ['assessment-service'],
    relatedPatterns: ['ml-scoring', 'anomaly-detection'],
    status: 'live',
    lastUpdated: '2026-03-06',
    monthlyRequests: '8M',
    tags: ['fraud', 'ml', 'compliance', 'risk'],
  },
  {
    id: 'risk-scoring-service',
    name: 'Risk Scoring Service',
    type: 'api',
    departmentId: 'rts',
    teamId: 'osprey-compliance',
    description:
      'Calculates risk scores for taxpayers and transactions based on multiple factors.',
    documentation: 'https://docs.demo.gov.example/risk-scoring',
    endpoint: 'https://api.revenue.demo.gov.example/risk/v1',
    version: '1.8.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['fraud-detection-api'],
    relatedPatterns: ['ml-scoring', 'feature-engineering'],
    status: 'live',
    lastUpdated: '2026-02-22',
    monthlyRequests: '15M',
    tags: ['risk', 'scoring', 'compliance'],
  },
  {
    id: 'compliance-rules-engine',
    name: 'Compliance Rules Engine',
    type: 'api',
    departmentId: 'rts',
    teamId: 'osprey-compliance',
    description:
      'Configurable rules engine for compliance checks and automated case routing.',
    documentation: 'https://docs.demo.gov.example/compliance-rules',
    endpoint: 'https://api.revenue.demo.gov.example/compliance/v1',
    version: '1.4.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['risk-scoring-service'],
    consumedBy: [],
    relatedPatterns: ['rules-engine', 'decision-tables'],
    status: 'live',
    lastUpdated: '2026-02-10',
    monthlyRequests: '5M',
    tags: ['compliance', 'rules', 'automation'],
  },
];

export default rtsServices;
