import type { Service } from '../schema';

/**
 * Vehicle & Licensing Authority (VLA) Services
 *
 * Vehicle registration, driving licences, and enquiry services.
 * Popular lookup services consumed by many external parties.
 */

export const vlaServices: Service[] = [
  // =========================================================================
  // Badger Vehicle Registry
  // =========================================================================
  {
    id: 'vehicle-register-api',
    name: 'Vehicle Register API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'badger-registry',
    description:
      'Core API for the national vehicle register. Handles registrations, transfers, and status updates.',
    documentation: 'https://docs.demo.gov.example/vehicle-register',
    endpoint: 'https://api.vehicles.demo.gov.example/register/v3',
    version: '3.4.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['vehicle-enquiry-api', 'trade-api', 'insurance-industry-feed'],
    relatedPatterns: ['event-sourcing', 'audit-logging'],
    status: 'live',
    lastUpdated: '2026-03-12',
    monthlyRequests: '45M',
    uptime: '99.97%',
    tags: ['vehicles', 'registration', 'core-system'],
  },
  {
    id: 'keeper-records-api',
    name: 'Keeper Records API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'badger-registry',
    description:
      'Manages vehicle keeper information and keeper-to-keeper transfers.',
    documentation: 'https://docs.demo.gov.example/keeper-records',
    endpoint: 'https://api.vehicles.demo.gov.example/keepers/v2',
    version: '2.2.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['vehicle-register-api'],
    consumedBy: ['vehicle-enquiry-api'],
    relatedPatterns: ['privacy-by-design', 'data-retention'],
    status: 'live',
    lastUpdated: '2026-03-05',
    monthlyRequests: '12M',
    tags: ['keepers', 'ownership', 'transfers'],
  },
  {
    id: 'vehicle-history-service',
    name: 'Vehicle History Service',
    type: 'api',
    departmentId: 'vla',
    teamId: 'badger-registry',
    description:
      'Provides MOT history, mileage records, and vehicle lifecycle information.',
    documentation: 'https://docs.demo.gov.example/vehicle-history',
    endpoint: 'https://api.vehicles.demo.gov.example/history/v2',
    version: '2.5.0',
    authentication: ['oauth2-client-credentials', 'api-key'],
    dependsOn: ['vehicle-register-api'],
    consumedBy: ['vehicle-enquiry-api'],
    relatedPatterns: ['data-aggregation', 'caching-strategy'],
    status: 'live',
    lastUpdated: '2026-02-28',
    monthlyRequests: '28M',
    tags: ['history', 'mot', 'mileage'],
  },
  {
    id: 'trade-api',
    name: 'Motor Trade API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'badger-registry',
    description:
      'Bulk APIs for motor traders to manage fleet registrations and transfers.',
    documentation: 'https://docs.demo.gov.example/trade-api',
    endpoint: 'https://api.vehicles.demo.gov.example/trade/v2',
    version: '2.1.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['vehicle-register-api'],
    consumedBy: [],
    relatedPatterns: ['batch-processing', 'rate-limiting'],
    status: 'live',
    lastUpdated: '2026-02-20',
    monthlyRequests: '8M',
    tags: ['trade', 'bulk', 'dealers'],
  },

  // =========================================================================
  // Otter Licensing Team
  // =========================================================================
  {
    id: 'licence-application-api',
    name: 'Licence Application API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'otter-licensing',
    description:
      'Handles driving licence applications, renewals, and amendments.',
    documentation: 'https://docs.demo.gov.example/licence-application',
    endpoint: 'https://api.vehicles.demo.gov.example/licence/v2',
    version: '2.4.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['gov-notify', 'gov-pay', 'identity-verification-api'],
    consumedBy: [],
    relatedPatterns: ['document-upload', 'photo-validation', 'payment-flow'],
    status: 'live',
    lastUpdated: '2026-03-08',
    monthlyRequests: '3.5M',
    tags: ['licence', 'applications', 'citizen-facing'],
  },
  {
    id: 'entitlement-check-api',
    name: 'Driving Entitlement Check API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'otter-licensing',
    description:
      'Verifies driving entitlements and licence validity for employers and insurers.',
    documentation: 'https://docs.demo.gov.example/entitlement-check',
    endpoint: 'https://api.vehicles.demo.gov.example/entitlement/v2',
    version: '2.0.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['driver-lookup-api', 'insurance-industry-feed'],
    relatedPatterns: ['consent-management', 'share-codes'],
    status: 'live',
    lastUpdated: '2026-03-01',
    monthlyRequests: '15M',
    tags: ['entitlement', 'verification', 'employers'],
  },
  {
    id: 'penalty-points-api',
    name: 'Penalty Points API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'otter-licensing',
    description:
      'Manages endorsements and penalty points on driving licences.',
    documentation: 'https://docs.demo.gov.example/penalty-points',
    endpoint: 'https://api.vehicles.demo.gov.example/points/v1',
    version: '1.6.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['entitlement-check-api', 'police-enquiry-api'],
    relatedPatterns: ['event-sourcing', 'court-integration'],
    status: 'live',
    lastUpdated: '2026-02-18',
    monthlyRequests: '5M',
    tags: ['penalty-points', 'endorsements', 'courts'],
  },
  {
    id: 'medical-fitness-api',
    name: 'Medical Fitness API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'otter-licensing',
    description:
      'Manages medical fitness declarations and notifiable conditions for drivers.',
    documentation: 'https://docs.demo.gov.example/medical-fitness',
    endpoint: 'https://api.vehicles.demo.gov.example/medical/v1',
    version: '1.3.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['entitlement-check-api'],
    relatedPatterns: ['sensitive-data', 'consent-management'],
    status: 'live',
    lastUpdated: '2026-02-10',
    monthlyRequests: '800K',
    tags: ['medical', 'fitness', 'health'],
  },

  // =========================================================================
  // Hare Enquiries Service
  // =========================================================================
  {
    id: 'vehicle-enquiry-api',
    name: 'Vehicle Enquiry API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'hare-enquiries',
    description:
      'Public API for checking vehicle tax, MOT status, and basic vehicle details.',
    documentation: 'https://docs.demo.gov.example/vehicle-enquiry',
    endpoint: 'https://api.vehicles.demo.gov.example/enquiry/v1',
    version: '1.8.0',
    authentication: ['api-key'],
    dependsOn: ['vehicle-register-api', 'keeper-records-api', 'vehicle-history-service', 'api-gateway'],
    consumedBy: [],
    relatedPatterns: ['rate-limiting', 'caching-strategy', 'public-api'],
    status: 'live',
    lastUpdated: '2026-03-10',
    monthlyRequests: '180M',
    uptime: '99.95%',
    tags: ['enquiry', 'public', 'tax', 'mot'],
  },
  {
    id: 'driver-lookup-api',
    name: 'Driver Lookup API',
    type: 'api',
    departmentId: 'vla',
    teamId: 'hare-enquiries',
    description:
      'Authorised lookup of driver details for employers, insurers, and police.',
    documentation: 'https://docs.demo.gov.example/driver-lookup',
    endpoint: 'https://api.vehicles.demo.gov.example/driver/v2',
    version: '2.1.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['entitlement-check-api'],
    consumedBy: ['police-enquiry-api'],
    relatedPatterns: ['consent-management', 'audit-logging'],
    status: 'live',
    lastUpdated: '2026-03-03',
    monthlyRequests: '22M',
    tags: ['driver', 'lookup', 'verification'],
  },
  {
    id: 'insurance-industry-feed',
    name: 'Insurance Industry Data Feed',
    type: 'event-stream',
    departmentId: 'vla',
    teamId: 'hare-enquiries',
    description:
      'Real-time feed of vehicle and licence data for motor insurers.',
    documentation: 'https://docs.demo.gov.example/insurance-feed',
    version: '3.0.0',
    authentication: ['mtls'],
    dependsOn: ['vehicle-register-api', 'entitlement-check-api'],
    consumedBy: [],
    relatedPatterns: ['event-streaming', 'data-contracts'],
    status: 'live',
    lastUpdated: '2026-02-25',
    monthlyRequests: '500M',
    tags: ['insurance', 'feed', 'real-time'],
  },
  {
    id: 'police-enquiry-api',
    name: 'Police National Computer Link',
    type: 'api',
    departmentId: 'vla',
    teamId: 'hare-enquiries',
    description:
      'Secure API for police forces to access vehicle and driver information.',
    documentation: 'https://docs.demo.gov.example/police-enquiry',
    endpoint: 'https://api.vehicles.demo.gov.example/police/v2',
    version: '2.3.0',
    authentication: ['mtls'],
    dependsOn: ['driver-lookup-api', 'penalty-points-api'],
    consumedBy: [],
    relatedPatterns: ['secure-api', 'audit-logging', 'rate-limiting'],
    status: 'live',
    lastUpdated: '2026-02-28',
    monthlyRequests: '35M',
    uptime: '99.99%',
    tags: ['police', 'secure', 'law-enforcement'],
  },
];

export default vlaServices;
