'use client';

/**
 * Export Summary Component
 *
 * Generates a downloadable summary for stakeholders.
 * Creates both Markdown and a printable view.
 */

import { useState } from 'react';
import {
  getComparisonStats,
  GOVUK_STATS,
  getGovernanceCoverage,
  getCapabilitySummary,
} from '@/lib/govuk-api';

function generateMarkdown(): string {
  const stats = getComparisonStats();
  const coverage = getGovernanceCoverage();
  const capSummary = getCapabilitySummary();
  const now = new Date().toISOString().split('T')[0];

  return `# Cross-Government API Discovery: Capability Assessment

**Date:** ${now}
**Source:** Wayfinder Demo Comparison Dashboard

---

## Executive Summary

This document compares the current capabilities of api.gov.uk with what becomes possible
through federated data architecture (Solid Pods) as demonstrated by Wayfinder.

---

## Current State: api.gov.uk

- **Total APIs catalogued:** ${stats.govuk.totalApis.toLocaleString()}
- **Providers/Departments:** ${stats.govuk.providers}
- **With documentation links:** ~${stats.govuk.withDocumentation.toLocaleString()}
- **Source:** ${GOVUK_STATS.source}

### Current Capabilities
- ✓ Searchable API catalogue
- ✓ Documentation links to department sites
- ✓ Provider/department identification
- ◐ Partial data sovereignty (docs hosted by depts, catalogue centralised)

### Current Limitations
- ✗ No service relationship tracking
- ✗ No policy governance visibility
- ✗ No team/people discovery
- ✗ No architecture patterns
- ✗ Not queryable by AI agents
- ✗ No granular access control

---

## Proposed Enhancement: Federated Data (Solid Pods)

### Additional Capabilities Demonstrated
- ✓ Service dependency graph (${stats.wayfinder.relationships} relationships)
- ✓ Policy → Service governance (${stats.wayfinder.policies} policies)
- ✓ Team discovery (${stats.wayfinder.teams} teams)
- ✓ People/expertise (${stats.wayfinder.people} profiles)
- ✓ Architecture patterns (${stats.wayfinder.patterns} patterns)
- ✓ Agent-queryable (natural language + SPARQL)
- ✓ Granular ACL per data field

### Governance Visibility (Demo Data)
- Total services: ${coverage.total}
- Governed by policy: ${coverage.governed} (${coverage.coveragePercent}%)
- Ungoverned: ${coverage.ungoverned} (${100 - coverage.coveragePercent}%)

---

## Capability Comparison

| Capability | api.gov.uk | Wayfinder |
|------------|------------|-----------|
| Available | ${capSummary.govuk.available} | ${capSummary.wayfinder.available} |
| Partial | ${capSummary.govuk.partial} | ${capSummary.wayfinder.partial} |
| Unavailable | ${capSummary.govuk.unavailable} | ${capSummary.wayfinder.unavailable} |

---

## Decisions Required

### 1. Agent Access
**Question:** Should AI agents be able to query the cross-government API landscape?

- **YES:** Requires structured data, relationship graph, query endpoint
- **NO:** Continues with HTML browsing, manual search

### 2. Governance Visibility
**Question:** Should services be linked to their governing policies?

- **YES:** Enables compliance auditing, gap detection, impact analysis
- **NO:** Accepts governance blind spots, manual tracking

### 3. Federated Data Ownership
**Question:** Should departments own their catalogue data (not just documentation)?

- **YES:** Enables real-time updates, granular ACL, department autonomy
- **NO:** Continues with central GitHub PR workflow

---

## Next Steps

If proceeding with evaluation:
1. Define pilot scope (single department or cross-cutting use case)
2. Identify stakeholder requirements for access control
3. Assess infrastructure requirements for Solid Pod deployment
4. Establish governance for schema interoperability

---

*Generated by Wayfinder Demo - ${now}*
*This document is provided to inform architectural decisions.*
`;
}

export function ExportSummary() {
  const [copied, setCopied] = useState(false);

  const handleDownload = () => {
    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wayfinder-comparison-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    const markdown = generateMarkdown();
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="govuk-!-margin-bottom-8">
      <h2 className="govuk-heading-l">Export Summary</h2>

      <p className="govuk-body">
        Download or copy a summary of this comparison for stakeholder review.
        The summary includes current state, proposed capabilities, and decision framework.
      </p>

      <div
        className="govuk-!-padding-4 govuk-!-margin-bottom-4"
        style={{ background: '#f3f2f1', border: '1px solid #b1b4b6' }}
      >
        <h3 className="govuk-heading-s">Stakeholder Summary Document</h3>
        <p className="govuk-body-s">
          A Markdown document suitable for sharing via email, Slack, or conversion to PDF.
          Includes capability matrix, governance analysis, and decision framework.
        </p>

        <div className="govuk-button-group">
          <button
            type="button"
            className="govuk-button"
            onClick={handleDownload}
          >
            Download Markdown
          </button>
          <button
            type="button"
            className="govuk-button govuk-button--secondary"
            onClick={handleCopy}
          >
            {copied ? 'Copied!' : 'Copy to clipboard'}
          </button>
          <button
            type="button"
            className="govuk-button govuk-button--secondary"
            onClick={handlePrint}
          >
            Print this page
          </button>
        </div>
      </div>

      <div className="govuk-inset-text">
        <strong>Tip:</strong> For PDF output, use the Print function and select
        &quot;Save as PDF&quot; as the destination. Most browsers support this natively.
      </div>
    </div>
  );
}
