import type { Service } from '../schema';

/**
 * Digital Standards Office (DSO) Services
 *
 * Core shared platforms that other departments consume.
 * These are the "foundation" services in the graph.
 */

export const dsoServices: Service[] = [
  // =========================================================================
  // Granite Platform Team
  // =========================================================================
  {
    id: 'api-gateway',
    name: 'Government API Gateway',
    type: 'platform',
    departmentId: 'dso',
    teamId: 'granite-platform',
    description:
      'Central API gateway providing authentication, rate limiting, and routing for all cross-government APIs. Handles 50M+ requests daily.',
    documentation: 'https://docs.demo.gov.example/api-gateway',
    endpoint: 'https://gateway.demo.gov.example',
    version: '3.2.1',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['secrets-manager'],
    consumedBy: [
      'eligibility-api',
      'income-verification-api',
      'identity-verification-api',
      'vehicle-enquiry-api',
    ],
    relatedPatterns: ['api-gateway-pattern', 'oauth2-client-credentials', 'rate-limiting'],
    status: 'live',
    lastUpdated: '2026-03-10',
    monthlyRequests: '1.5B',
    uptime: '99.99%',
    tags: ['infrastructure', 'api', 'gateway', 'authentication', 'shared-platform'],
  },
  {
    id: 'service-mesh',
    name: 'Cross-Government Service Mesh',
    type: 'platform',
    departmentId: 'dso',
    teamId: 'granite-platform',
    description:
      'Istio-based service mesh providing mTLS, observability, and traffic management for microservices across government.',
    documentation: 'https://docs.demo.gov.example/service-mesh',
    version: '2.1.0',
    authentication: ['mtls'],
    dependsOn: ['cloud-platform'],
    consumedBy: [],
    relatedPatterns: ['service-mesh-pattern', 'mtls-everywhere', 'circuit-breaker'],
    status: 'live',
    lastUpdated: '2026-02-28',
    uptime: '99.97%',
    tags: ['infrastructure', 'mesh', 'security', 'observability'],
  },
  {
    id: 'cloud-platform',
    name: 'Government Cloud Platform',
    type: 'platform',
    departmentId: 'dso',
    teamId: 'granite-platform',
    description:
      'Kubernetes-based hosting platform for government services. Provides standardised deployment, scaling, and monitoring.',
    documentation: 'https://docs.demo.gov.example/cloud-platform',
    version: '4.0.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: [],
    consumedBy: ['dcs-platform', 'service-mesh'],
    relatedPatterns: ['twelve-factor-app', 'infrastructure-as-code'],
    status: 'live',
    lastUpdated: '2026-03-01',
    tags: ['infrastructure', 'hosting', 'kubernetes', 'platform'],
  },
  {
    id: 'secrets-manager',
    name: 'Government Secrets Manager',
    type: 'platform',
    departmentId: 'dso',
    teamId: 'granite-platform',
    description:
      'Centralised secrets management using HashiCorp Vault. Provides API keys, certificates, and credential rotation.',
    documentation: 'https://docs.demo.gov.example/secrets-manager',
    endpoint: 'https://secrets.demo.gov.example',
    version: '1.8.0',
    authentication: ['mtls', 'jwt-bearer'],
    dependsOn: [],
    consumedBy: ['api-gateway', 'gov-notify', 'gov-pay'],
    relatedPatterns: ['secrets-management', 'credential-rotation'],
    status: 'live',
    lastUpdated: '2026-01-15',
    tags: ['security', 'secrets', 'credentials', 'vault'],
  },

  // =========================================================================
  // Cedar Design System
  // =========================================================================
  {
    id: 'design-system',
    name: 'Government Design System',
    type: 'library',
    departmentId: 'dso',
    teamId: 'cedar-design',
    description:
      'Official design system with accessible components, patterns, and styles for government services. Used by 200+ services.',
    documentation: 'https://design.demo.gov.example',
    version: '5.1.0',
    dependsOn: [],
    consumedBy: ['citizen-portal', 'rts-developer-portal'],
    relatedPatterns: ['accessible-forms', 'progressive-enhancement', 'mobile-first'],
    status: 'live',
    lastUpdated: '2026-03-12',
    tags: ['design', 'frontend', 'accessibility', 'components', 'ui'],
  },
  {
    id: 'component-library',
    name: 'React Component Library',
    type: 'library',
    departmentId: 'dso',
    teamId: 'cedar-design',
    description:
      'React implementation of the design system. Type-safe, accessible components with built-in validation.',
    documentation: 'https://components.demo.gov.example',
    version: '3.4.0',
    dependsOn: ['design-system'],
    consumedBy: ['citizen-portal'],
    relatedPatterns: ['accessible-forms', 'error-handling-ui'],
    status: 'live',
    lastUpdated: '2026-03-08',
    tags: ['react', 'components', 'typescript', 'frontend'],
  },
  {
    id: 'prototype-kit',
    name: 'Service Prototype Kit',
    type: 'library',
    departmentId: 'dso',
    teamId: 'cedar-design',
    description:
      'Rapid prototyping tool for testing service designs with users. Includes example patterns and data.',
    documentation: 'https://prototype-kit.demo.gov.example',
    version: '14.2.0',
    dependsOn: ['design-system'],
    consumedBy: [],
    relatedPatterns: ['user-research-patterns'],
    status: 'live',
    lastUpdated: '2026-02-20',
    tags: ['prototyping', 'user-research', 'design'],
  },
  {
    id: 'accessibility-checker',
    name: 'Automated Accessibility Checker',
    type: 'api',
    departmentId: 'dso',
    teamId: 'cedar-design',
    description:
      'API for automated WCAG 2.1 AA compliance checking. Integrates with CI/CD pipelines.',
    documentation: 'https://docs.demo.gov.example/accessibility-checker',
    endpoint: 'https://a11y-check.demo.gov.example/api/v1',
    version: '2.0.0',
    authentication: ['api-key'],
    dependsOn: [],
    consumedBy: ['ci-cd-service'],
    relatedPatterns: ['accessibility-testing'],
    status: 'live',
    lastUpdated: '2026-01-30',
    monthlyRequests: '2.1M',
    tags: ['accessibility', 'testing', 'wcag', 'automation'],
  },

  // =========================================================================
  // Birch Notifications
  // =========================================================================
  {
    id: 'gov-notify',
    name: 'Government Notify',
    type: 'api',
    departmentId: 'dso',
    teamId: 'birch-notify',
    description:
      'Cross-government notification service for emails, SMS, and letters. Sends 100M+ messages monthly.',
    documentation: 'https://docs.demo.gov.example/notify',
    endpoint: 'https://api.notify.demo.gov.example/v2',
    version: '2.8.0',
    authentication: ['api-key'],
    dependsOn: ['secrets-manager', 'template-service'],
    consumedBy: [
      'citizen-portal',
      'application-service',
      'passport-application-api',
      'licence-application-api',
    ],
    relatedPatterns: ['async-notifications', 'template-management', 'delivery-receipts'],
    status: 'live',
    lastUpdated: '2026-03-05',
    monthlyRequests: '100M',
    uptime: '99.95%',
    tags: ['notifications', 'email', 'sms', 'letters', 'shared-platform'],
  },
  {
    id: 'template-service',
    name: 'Notification Template Service',
    type: 'api',
    departmentId: 'dso',
    teamId: 'birch-notify',
    description:
      'Manages notification templates with versioning, personalisation, and approval workflows.',
    documentation: 'https://docs.demo.gov.example/notify/templates',
    endpoint: 'https://api.notify.demo.gov.example/templates/v1',
    version: '1.5.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: [],
    consumedBy: ['gov-notify'],
    relatedPatterns: ['template-management'],
    status: 'live',
    lastUpdated: '2026-02-18',
    tags: ['templates', 'notifications', 'content-management'],
  },
  {
    id: 'delivery-receipts',
    name: 'Delivery Receipts API',
    type: 'api',
    departmentId: 'dso',
    teamId: 'birch-notify',
    description:
      'Webhook and polling API for tracking notification delivery status and failures.',
    documentation: 'https://docs.demo.gov.example/notify/receipts',
    endpoint: 'https://api.notify.demo.gov.example/receipts/v1',
    version: '1.2.0',
    authentication: ['api-key'],
    dependsOn: ['gov-notify'],
    consumedBy: ['case-management'],
    relatedPatterns: ['webhook-patterns', 'delivery-receipts'],
    status: 'live',
    lastUpdated: '2026-01-22',
    monthlyRequests: '45M',
    tags: ['webhooks', 'status', 'notifications'],
  },

  // =========================================================================
  // Willow Payments
  // =========================================================================
  {
    id: 'gov-pay',
    name: 'Government Pay',
    type: 'api',
    departmentId: 'dso',
    teamId: 'willow-pay',
    description:
      'Shared payment platform for taking card payments and Direct Debit. PCI-DSS compliant.',
    documentation: 'https://docs.demo.gov.example/pay',
    endpoint: 'https://api.pay.demo.gov.example/v1',
    version: '2.5.0',
    authentication: ['api-key'],
    dependsOn: ['secrets-manager'],
    consumedBy: ['citizen-portal', 'passport-application-api', 'licence-application-api'],
    relatedPatterns: ['payment-flow', 'idempotency-keys', 'pci-compliance'],
    status: 'live',
    lastUpdated: '2026-03-02',
    monthlyRequests: '8.5M',
    uptime: '99.99%',
    tags: ['payments', 'card', 'direct-debit', 'pci', 'shared-platform'],
  },
  {
    id: 'refund-service',
    name: 'Refund Processing Service',
    type: 'api',
    departmentId: 'dso',
    teamId: 'willow-pay',
    description:
      'Processes refunds for payments made through Government Pay. Supports partial and full refunds.',
    documentation: 'https://docs.demo.gov.example/pay/refunds',
    endpoint: 'https://api.pay.demo.gov.example/refunds/v1',
    version: '1.3.0',
    authentication: ['api-key'],
    dependsOn: ['gov-pay'],
    consumedBy: ['case-management'],
    relatedPatterns: ['idempotency-keys'],
    status: 'live',
    lastUpdated: '2026-02-10',
    monthlyRequests: '450K',
    tags: ['payments', 'refunds'],
  },
  {
    id: 'reconciliation-api',
    name: 'Payment Reconciliation API',
    type: 'api',
    departmentId: 'dso',
    teamId: 'willow-pay',
    description:
      'Daily reconciliation reports and APIs for matching payments to internal records.',
    documentation: 'https://docs.demo.gov.example/pay/reconciliation',
    endpoint: 'https://api.pay.demo.gov.example/reconciliation/v1',
    version: '1.1.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['gov-pay'],
    consumedBy: ['reporting-api'],
    relatedPatterns: ['batch-processing', 'reconciliation-patterns'],
    status: 'live',
    lastUpdated: '2026-01-28',
    tags: ['payments', 'reconciliation', 'finance'],
  },
];

export default dsoServices;
