import type { Service } from '../schema';

/**
 * National Health Data Service (NHDS) Services
 *
 * Health records, prescriptions, and clinical data services.
 * Critical infrastructure with strict data governance.
 */

export const nhdsServices: Service[] = [
  // =========================================================================
  // Oak Health Records
  // =========================================================================
  {
    id: 'summary-care-record-api',
    name: 'Summary Care Record API',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'oak-records',
    description:
      'Provides access to patient summary care records including medications, allergies, and adverse reactions.',
    documentation: 'https://docs.demo.gov.example/scr',
    endpoint: 'https://api.health-data.demo.gov.example/scr/v2',
    version: '2.4.0',
    authentication: ['oauth2-authorization-code', 'mtls'],
    dependsOn: ['record-access-api', 'patient-demographics-api'],
    consumedBy: ['health-info-exchange'],
    relatedPatterns: ['consent-management', 'break-glass-access', 'audit-logging'],
    status: 'live',
    lastUpdated: '2026-03-11',
    monthlyRequests: '45M',
    uptime: '99.99%',
    tags: ['health', 'scr', 'clinical', 'patient-data'],
  },
  {
    id: 'health-info-exchange',
    name: 'Health Information Exchange',
    type: 'platform',
    departmentId: 'nhds',
    teamId: 'oak-records',
    description:
      'Central hub for sharing clinical information between healthcare providers using FHIR standards.',
    documentation: 'https://docs.demo.gov.example/hie',
    endpoint: 'https://api.health-data.demo.gov.example/hie/v1',
    version: '1.8.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['summary-care-record-api', 'fhir-api-platform'],
    consumedBy: [],
    relatedPatterns: ['fhir-resources', 'event-driven-integration'],
    status: 'live',
    lastUpdated: '2026-03-08',
    monthlyRequests: '120M',
    tags: ['hie', 'interoperability', 'fhir'],
  },
  {
    id: 'patient-demographics-api',
    name: 'Patient Demographics Service',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'oak-records',
    description:
      'Master patient index providing demographics, NHS number lookup, and patient matching.',
    documentation: 'https://docs.demo.gov.example/pds',
    endpoint: 'https://api.health-data.demo.gov.example/pds/v2',
    version: '2.6.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['summary-care-record-api', 'electronic-prescription-api', 'health-info-exchange'],
    relatedPatterns: ['patient-matching', 'data-quality'],
    status: 'live',
    lastUpdated: '2026-03-05',
    monthlyRequests: '85M',
    uptime: '99.99%',
    tags: ['demographics', 'pds', 'nhs-number'],
  },
  {
    id: 'record-access-api',
    name: 'Record Access Control API',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'oak-records',
    description:
      'Manages patient consent and access permissions for health record sharing.',
    documentation: 'https://docs.demo.gov.example/record-access',
    endpoint: 'https://api.health-data.demo.gov.example/access/v1',
    version: '1.5.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: [],
    consumedBy: ['summary-care-record-api'],
    relatedPatterns: ['consent-management', 'access-control'],
    status: 'live',
    lastUpdated: '2026-02-25',
    monthlyRequests: '15M',
    tags: ['consent', 'access-control', 'privacy'],
  },

  // =========================================================================
  // Elm Prescriptions Platform
  // =========================================================================
  {
    id: 'electronic-prescription-api',
    name: 'Electronic Prescription Service API',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'elm-prescriptions',
    description:
      'Manages electronic prescriptions from prescriber to dispenser.',
    documentation: 'https://docs.demo.gov.example/eps',
    endpoint: 'https://api.health-data.demo.gov.example/eps/v2',
    version: '2.8.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['patient-demographics-api'],
    consumedBy: ['dispensing-service', 'medication-record-api'],
    relatedPatterns: ['digital-signatures', 'workflow-patterns'],
    status: 'live',
    lastUpdated: '2026-03-10',
    monthlyRequests: '95M',
    uptime: '99.97%',
    tags: ['eps', 'prescriptions', 'pharmacy'],
  },
  {
    id: 'dispensing-service',
    name: 'Dispensing Notification Service',
    type: 'event-stream',
    departmentId: 'nhds',
    teamId: 'elm-prescriptions',
    description:
      'Real-time notifications when prescriptions are dispensed by pharmacies.',
    documentation: 'https://docs.demo.gov.example/dispensing',
    version: '1.6.0',
    authentication: ['mtls'],
    dependsOn: ['electronic-prescription-api'],
    consumedBy: ['medication-record-api'],
    relatedPatterns: ['event-streaming', 'exactly-once-processing'],
    status: 'live',
    lastUpdated: '2026-03-03',
    monthlyRequests: '80M',
    tags: ['dispensing', 'pharmacy', 'real-time'],
  },
  {
    id: 'medication-record-api',
    name: 'Medication Record API',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'elm-prescriptions',
    description:
      'Consolidated view of patient medication history from prescriptions and dispensing.',
    documentation: 'https://docs.demo.gov.example/medication-record',
    endpoint: 'https://api.health-data.demo.gov.example/medications/v1',
    version: '1.4.0',
    authentication: ['oauth2-authorization-code', 'mtls'],
    dependsOn: ['electronic-prescription-api', 'dispensing-service'],
    consumedBy: ['summary-care-record-api'],
    relatedPatterns: ['data-aggregation', 'caching-strategy'],
    status: 'live',
    lastUpdated: '2026-02-28',
    monthlyRequests: '25M',
    tags: ['medications', 'history', 'clinical'],
  },

  // =========================================================================
  // Ash Integration Services
  // =========================================================================
  {
    id: 'fhir-api-platform',
    name: 'FHIR API Platform',
    type: 'platform',
    departmentId: 'nhds',
    teamId: 'ash-integration',
    description:
      'FHIR R4 compliant API platform for healthcare interoperability.',
    documentation: 'https://docs.demo.gov.example/fhir',
    endpoint: 'https://api.health-data.demo.gov.example/fhir/R4',
    version: '4.2.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['health-info-exchange', 'integration-toolkit'],
    relatedPatterns: ['fhir-resources', 'smart-on-fhir'],
    status: 'live',
    lastUpdated: '2026-03-09',
    monthlyRequests: '150M',
    uptime: '99.95%',
    tags: ['fhir', 'interoperability', 'hl7', 'standards'],
  },
  {
    id: 'message-router',
    name: 'Clinical Message Router',
    type: 'platform',
    departmentId: 'nhds',
    teamId: 'ash-integration',
    description:
      'Routes clinical messages between healthcare systems using ITK3 and MESH protocols.',
    documentation: 'https://docs.demo.gov.example/message-router',
    version: '3.1.0',
    authentication: ['mtls'],
    dependsOn: [],
    consumedBy: ['health-info-exchange'],
    relatedPatterns: ['message-routing', 'guaranteed-delivery'],
    status: 'live',
    lastUpdated: '2026-02-22',
    monthlyRequests: '200M',
    tags: ['messaging', 'itk3', 'mesh', 'routing'],
  },
  {
    id: 'legacy-adapters',
    name: 'Legacy System Adapters',
    type: 'library',
    departmentId: 'nhds',
    teamId: 'ash-integration',
    description:
      'Collection of adapters for integrating with legacy health systems (HL7v2, GP Connect, etc).',
    documentation: 'https://docs.demo.gov.example/legacy-adapters',
    version: '2.5.0',
    dependsOn: [],
    consumedBy: ['health-info-exchange', 'message-router'],
    relatedPatterns: ['adapter-pattern', 'protocol-translation'],
    status: 'live',
    lastUpdated: '2026-02-15',
    tags: ['legacy', 'adapters', 'hl7', 'gp-connect'],
  },
  {
    id: 'integration-toolkit',
    name: 'NHDS Integration Toolkit',
    type: 'library',
    departmentId: 'nhds',
    teamId: 'ash-integration',
    description:
      'SDK and tools for healthcare suppliers integrating with NHDS APIs.',
    documentation: 'https://docs.demo.gov.example/integration-toolkit',
    version: '3.0.0',
    dependsOn: ['fhir-api-platform'],
    consumedBy: [],
    relatedPatterns: ['developer-experience', 'api-documentation'],
    status: 'live',
    lastUpdated: '2026-03-01',
    tags: ['sdk', 'toolkit', 'developers'],
  },

  // =========================================================================
  // Maple Health Analytics
  // =========================================================================
  {
    id: 'population-health-api',
    name: 'Population Health API',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'maple-analytics',
    description:
      'Aggregated, anonymised population health statistics for planning and research.',
    documentation: 'https://docs.demo.gov.example/population-health',
    endpoint: 'https://api.health-data.demo.gov.example/population/v1',
    version: '1.6.0',
    authentication: ['oauth2-client-credentials'],
    dependsOn: ['anonymisation-service'],
    consumedBy: ['health-dashboards'],
    relatedPatterns: ['data-aggregation', 'statistical-disclosure'],
    status: 'live',
    lastUpdated: '2026-03-06',
    monthlyRequests: '2M',
    tags: ['population', 'analytics', 'statistics'],
  },
  {
    id: 'anonymisation-service',
    name: 'Health Data Anonymisation Service',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'maple-analytics',
    description:
      'De-identifies health data for secondary use in research and analytics.',
    documentation: 'https://docs.demo.gov.example/anonymisation',
    endpoint: 'https://api.health-data.demo.gov.example/anon/v1',
    version: '1.3.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: [],
    consumedBy: ['population-health-api', 'research-data-api'],
    relatedPatterns: ['k-anonymity', 'differential-privacy'],
    status: 'live',
    lastUpdated: '2026-02-20',
    monthlyRequests: '5M',
    tags: ['anonymisation', 'privacy', 'de-identification'],
  },
  {
    id: 'research-data-api',
    name: 'Research Data Access API',
    type: 'api',
    departmentId: 'nhds',
    teamId: 'maple-analytics',
    description:
      'Secure access to anonymised health datasets for approved research projects.',
    documentation: 'https://docs.demo.gov.example/research-data',
    endpoint: 'https://api.health-data.demo.gov.example/research/v1',
    version: '1.2.0',
    authentication: ['oauth2-client-credentials', 'mtls'],
    dependsOn: ['anonymisation-service'],
    consumedBy: [],
    relatedPatterns: ['data-governance', 'access-approval'],
    status: 'live',
    lastUpdated: '2026-02-12',
    monthlyRequests: '500K',
    tags: ['research', 'data-access', 'governance'],
  },
  {
    id: 'health-dashboards',
    name: 'Health Analytics Dashboards',
    type: 'platform',
    departmentId: 'nhds',
    teamId: 'maple-analytics',
    description:
      'Interactive dashboards for health system performance and population health metrics.',
    documentation: 'https://docs.demo.gov.example/health-dashboards',
    endpoint: 'https://dashboards.health-data.demo.gov.example',
    version: '2.4.0',
    authentication: ['oauth2-authorization-code'],
    dependsOn: ['population-health-api'],
    consumedBy: [],
    relatedPatterns: ['dashboard-patterns', 'data-visualisation'],
    status: 'live',
    lastUpdated: '2026-03-04',
    tags: ['dashboards', 'analytics', 'visualisation'],
  },
];

export default nhdsServices;
